name: nyc_airbnb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pydantic
  - pytest
  - pyyaml
  - pip:
      - hydra-core==1.3.2
      - mlflow==2.4.0
      - wandb==0.22.0
