main:
  components_repository: "https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components"
  project_name: nyc_airbnb
  experiment_name: development
  steps: all

etl:
  sample: 1.0

basic_cleaning:
  min_price: 10
  max_price: 350

data_check:
  kl_threshold: 0.2
  min_price: 10
  max_price: 350

data_split:
  test_size: 0.2
  val_size: 0.2
  random_state: 42
  stratify_by: neighbourhood_group
  max_tfidf_features: 5

modeling:
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1
    criterion: squared_error
    max_features: 0.5
    oob_score: true
