name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.14.2
      - scikit-learn
      - pandas
      - numpy
      - wandb
      - cloudpickle
      - matplotlib
